future: true
permalink: /:title/
url: http://superashan.github.io
name: 超级山子
author: superashan
qq: 
email: wt827357393@gmail.com
duoshuo: superashan
beian: 
cnzz: 
weibo: superashan
github: superashan
paginate: 20
highlighter: rouge
truncate: true
about: "超级山子(superashan)"
